"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from cribl_control_plane import CriblControlPlane, models
import os
from tests.test_client import create_test_http_client


def test_workers_sdk_get_summary_workers():
    test_http_client = create_test_http_client("getSummaryWorkers")

    with CriblControlPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("CRIBLCONTROLPLANE_BEARER_AUTH", "value"),
        ),
    ) as ccp_client:
        assert ccp_client is not None

        res = ccp_client.workers.get_summary_workers()
        assert res is not None
        assert res == models.GetSummaryWorkersResponse()


def test_workers_sdk_get_workers():
    test_http_client = create_test_http_client("getWorkers")

    with CriblControlPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("CRIBLCONTROLPLANE_BEARER_AUTH", "value"),
        ),
    ) as ccp_client:
        assert ccp_client is not None

        res = ccp_client.workers.get_workers()
        assert res is not None
        assert res == models.GetWorkersResponse()


def test_workers_sdk_update_workers_restart():
    test_http_client = create_test_http_client("updateWorkersRestart")

    with CriblControlPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("CRIBLCONTROLPLANE_BEARER_AUTH", "value"),
        ),
    ) as ccp_client:
        assert ccp_client is not None

        res = ccp_client.workers.update_workers_restart()
        assert res is not None
        assert res == models.UpdateWorkersRestartResponse()
