"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from cribl_control_plane import CriblControlPlane, models
import os
from tests.test_client import create_test_http_client


def test_health_get_health_info():
    test_http_client = create_test_http_client("getHealthInfo")

    with CriblControlPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
    ) as ccp_client:
        assert ccp_client is not None

        res = ccp_client.health.get_health_info()
        assert res is not None
        assert res.status == models.HealthStatusStatus.HEALTHY
