"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from cribl_control_plane import CriblControlPlane, models
import os
from tests.test_client import create_test_http_client


def test_auth_login():
    test_http_client = create_test_http_client("login")

    with CriblControlPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
    ) as ccp_client:
        assert ccp_client is not None

        res = ccp_client.auth.login(
            username="Nikko.Connelly", password="Ljp4BunfMR9hNyM"
        )
        assert res is not None
        assert res == models.AuthToken(
            token="<value>",
        )
