"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from cribl_control_plane import CriblControlPlane, models
import os
from tests.test_client import create_test_http_client


def test_teams_get_products_groups_acl_teams_by_product_and_id():
    test_http_client = create_test_http_client(
        "getProductsGroupsAclTeamsByProductAndId"
    )

    with CriblControlPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("CRIBLCONTROLPLANE_BEARER_AUTH", "value"),
        ),
    ) as ccp_client:
        assert ccp_client is not None

        res = ccp_client.teams.get_products_groups_acl_teams_by_product_and_id(
            product=models.GetProductsGroupsACLTeamsByProductAndIDProduct.STREAM,
            id="<id>",
        )
        assert res is not None
        assert res == models.GetProductsGroupsACLTeamsByProductAndIDResponse()
