"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from cribl_control_plane import CriblControlPlane
import os
from tests.test_client import create_test_http_client


def test_login_login():
    test_http_client = create_test_http_client("login")

    with CriblControlPlane(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
    ) as ccp_client:
        assert ccp_client is not None

        authenticate_res = ccp_client.auth.login(username="admin", password="admin")
        assert authenticate_res is not None
