// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CacheConnection struct {
	AcceleratedFields       []string                       `json:"acceleratedFields,omitempty"`
	BackfillStatus          *CacheConnectionBackfillStatus `json:"backfillStatus,omitempty"`
	CacheRef                string                         `json:"cacheRef"`
	CreatedAt               float64                        `json:"createdAt"`
	LakehouseConnectionType *LakehouseConnectionType       `json:"lakehouseConnectionType,omitempty"`
	MigrationQueryID        *string                        `json:"migrationQueryId,omitempty"`
	RetentionInDays         float64                        `json:"retentionInDays"`
}

func (o *CacheConnection) GetAcceleratedFields() []string {
	if o == nil {
		return nil
	}
	return o.AcceleratedFields
}

func (o *CacheConnection) GetBackfillStatus() *CacheConnectionBackfillStatus {
	if o == nil {
		return nil
	}
	return o.BackfillStatus
}

func (o *CacheConnection) GetCacheRef() string {
	if o == nil {
		return ""
	}
	return o.CacheRef
}

func (o *CacheConnection) GetCreatedAt() float64 {
	if o == nil {
		return 0.0
	}
	return o.CreatedAt
}

func (o *CacheConnection) GetLakehouseConnectionType() *LakehouseConnectionType {
	if o == nil {
		return nil
	}
	return o.LakehouseConnectionType
}

func (o *CacheConnection) GetMigrationQueryID() *string {
	if o == nil {
		return nil
	}
	return o.MigrationQueryID
}

func (o *CacheConnection) GetRetentionInDays() float64 {
	if o == nil {
		return 0.0
	}
	return o.RetentionInDays
}
