// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConfigGroupLookupsLookup struct {
	DeployedVersion *string `json:"deployedVersion,omitempty"`
	File            string  `json:"file"`
	Version         *string `json:"version,omitempty"`
}

func (o *ConfigGroupLookupsLookup) GetDeployedVersion() *string {
	if o == nil {
		return nil
	}
	return o.DeployedVersion
}

func (o *ConfigGroupLookupsLookup) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

func (o *ConfigGroupLookupsLookup) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

type ConfigGroupLookups struct {
	Context string                     `json:"context"`
	Lookups []ConfigGroupLookupsLookup `json:"lookups"`
}

func (o *ConfigGroupLookups) GetContext() string {
	if o == nil {
		return ""
	}
	return o.Context
}

func (o *ConfigGroupLookups) GetLookups() []ConfigGroupLookupsLookup {
	if o == nil {
		return []ConfigGroupLookupsLookup{}
	}
	return o.Lookups
}
