// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeployRequest struct {
	Lookups []DeployRequestLookups `json:"lookups,omitempty"`
	Version string                 `json:"version"`
}

func (o *DeployRequest) GetLookups() []DeployRequestLookups {
	if o == nil {
		return nil
	}
	return o.Lookups
}

func (o *DeployRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}
