// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeployRequestLookupsLookup struct {
	File    string `json:"file"`
	Version string `json:"version"`
}

func (o *DeployRequestLookupsLookup) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

func (o *DeployRequestLookupsLookup) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type DeployRequestLookups struct {
	Context string                       `json:"context"`
	Lookups []DeployRequestLookupsLookup `json:"lookups"`
}

func (o *DeployRequestLookups) GetContext() string {
	if o == nil {
		return ""
	}
	return o.Context
}

func (o *DeployRequestLookups) GetLookups() []DeployRequestLookupsLookup {
	if o == nil {
		return []DeployRequestLookupsLookup{}
	}
	return o.Lookups
}
