// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LoginInfo struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (o *LoginInfo) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *LoginInfo) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}
