// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type OutputSamplesResponse struct {
	Events []map[string]any `json:"events"`
}

func (o *OutputSamplesResponse) GetEvents() []map[string]any {
	if o == nil {
		return []map[string]any{}
	}
	return o.Events
}
