// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TeamAccessControlList struct {
	Perms []ResourcePolicy `json:"perms"`
	Team  string           `json:"team"`
}

func (o *TeamAccessControlList) GetPerms() []ResourcePolicy {
	if o == nil {
		return []ResourcePolicy{}
	}
	return o.Perms
}

func (o *TeamAccessControlList) GetTeam() string {
	if o == nil {
		return ""
	}
	return o.Team
}
