"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane import utils
from cribl_control_plane.models import healthstatus as models_healthstatus
from cribl_control_plane.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated


class HealthStatusErrorData(BaseModel):
    status: models_healthstatus.Status

    start_time: Annotated[float, pydantic.Field(alias="startTime")]

    role: Optional[models_healthstatus.Role] = None


class HealthStatusError(Exception):
    data: HealthStatusErrorData

    def __init__(self, data: HealthStatusErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, HealthStatusErrorData)
