// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateVersionUndoRequest struct {
	// Group ID
	Group *string `queryParam:"style=form,explode=true,name=group"`
}

func (o *CreateVersionUndoRequest) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

// CreateVersionUndoResponseBody - a list of object objects
type CreateVersionUndoResponseBody struct {
	// number of items present in the items array
	Count *int64   `json:"count,omitempty"`
	Items []string `json:"items,omitempty"`
}

func (o *CreateVersionUndoResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateVersionUndoResponseBody) GetItems() []string {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateVersionUndoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of object objects
	Object *CreateVersionUndoResponseBody
}

func (o *CreateVersionUndoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateVersionUndoResponse) GetObject() *CreateVersionUndoResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
