// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateVersionCommitResponseBody - a list of GitCommitSummary objects
type CreateVersionCommitResponseBody struct {
	// number of items present in the items array
	Count *int64                        `json:"count,omitempty"`
	Items []components.GitCommitSummary `json:"items,omitempty"`
}

func (o *CreateVersionCommitResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateVersionCommitResponseBody) GetItems() []components.GitCommitSummary {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateVersionCommitResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of GitCommitSummary objects
	Object *CreateVersionCommitResponseBody
}

func (o *CreateVersionCommitResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateVersionCommitResponse) GetObject() *CreateVersionCommitResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
