// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateRoutesAppendByIDRequest struct {
	// the route table to be appended to - currently default is the only supported value
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// RouteDefinitions object
	RequestBody []components.RouteConf `request:"mediaType=application/json"`
}

func (o *CreateRoutesAppendByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateRoutesAppendByIDRequest) GetRequestBody() []components.RouteConf {
	if o == nil {
		return []components.RouteConf{}
	}
	return o.RequestBody
}

// CreateRoutesAppendByIDResponseBody - a list of any objects
type CreateRoutesAppendByIDResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *CreateRoutesAppendByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateRoutesAppendByIDResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateRoutesAppendByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *CreateRoutesAppendByIDResponseBody
}

func (o *CreateRoutesAppendByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateRoutesAppendByIDResponse) GetObject() *CreateRoutesAppendByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
