// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreatePacksResponseBody - a list of PackInstallInfo objects
type CreatePacksResponseBody struct {
	// number of items present in the items array
	Count *int64                       `json:"count,omitempty"`
	Items []components.PackInstallInfo `json:"items,omitempty"`
}

func (o *CreatePacksResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreatePacksResponseBody) GetItems() []components.PackInstallInfo {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreatePacksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of PackInstallInfo objects
	Object *CreatePacksResponseBody
}

func (o *CreatePacksResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePacksResponse) GetObject() *CreatePacksResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
