// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateCriblLakeDatasetByLakeIDRequest struct {
	// lake id that contains the Datasets
	LakeID string `pathParam:"style=simple,explode=false,name=lakeId"`
	// CriblLakeDataset object
	CriblLakeDataset components.CriblLakeDataset `request:"mediaType=application/json"`
}

func (o *CreateCriblLakeDatasetByLakeIDRequest) GetLakeID() string {
	if o == nil {
		return ""
	}
	return o.LakeID
}

func (o *CreateCriblLakeDatasetByLakeIDRequest) GetCriblLakeDataset() components.CriblLakeDataset {
	if o == nil {
		return components.CriblLakeDataset{}
	}
	return o.CriblLakeDataset
}

// CreateCriblLakeDatasetByLakeIDResponseBody - a list of CriblLakeDataset objects
type CreateCriblLakeDatasetByLakeIDResponseBody struct {
	// number of items present in the items array
	Count *int64                        `json:"count,omitempty"`
	Items []components.CriblLakeDataset `json:"items,omitempty"`
}

func (o *CreateCriblLakeDatasetByLakeIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateCriblLakeDatasetByLakeIDResponseBody) GetItems() []components.CriblLakeDataset {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateCriblLakeDatasetByLakeIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of CriblLakeDataset objects
	Object *CreateCriblLakeDatasetByLakeIDResponseBody
}

func (o *CreateCriblLakeDatasetByLakeIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCriblLakeDatasetByLakeIDResponse) GetObject() *CreateCriblLakeDatasetByLakeIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
