// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateVersionRevertRequest struct {
	// Group ID
	Group *string `queryParam:"style=form,explode=true,name=group"`
	// GitRevertParams object
	GitRevertParams components.GitRevertParams `request:"mediaType=application/json"`
}

func (o *CreateVersionRevertRequest) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *CreateVersionRevertRequest) GetGitRevertParams() components.GitRevertParams {
	if o == nil {
		return components.GitRevertParams{}
	}
	return o.GitRevertParams
}

// CreateVersionRevertResponseBody - a list of GitRevertResult objects
type CreateVersionRevertResponseBody struct {
	// number of items present in the items array
	Count *int64                       `json:"count,omitempty"`
	Items []components.GitRevertResult `json:"items,omitempty"`
}

func (o *CreateVersionRevertResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateVersionRevertResponseBody) GetItems() []components.GitRevertResult {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateVersionRevertResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of GitRevertResult objects
	Object *CreateVersionRevertResponseBody
}

func (o *CreateVersionRevertResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateVersionRevertResponse) GetObject() *CreateVersionRevertResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
