// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateOutputTestByIDRequest struct {
	// Output Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// OutputTestRequest object
	OutputTestRequest components.OutputTestRequest `request:"mediaType=application/json"`
}

func (o *CreateOutputTestByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateOutputTestByIDRequest) GetOutputTestRequest() components.OutputTestRequest {
	if o == nil {
		return components.OutputTestRequest{}
	}
	return o.OutputTestRequest
}

// CreateOutputTestByIDResponseBody - a list of OutputTestResponse objects
type CreateOutputTestByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                          `json:"count,omitempty"`
	Items []components.OutputTestResponse `json:"items,omitempty"`
}

func (o *CreateOutputTestByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateOutputTestByIDResponseBody) GetItems() []components.OutputTestResponse {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateOutputTestByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of OutputTestResponse objects
	Object *CreateOutputTestByIDResponseBody
}

func (o *CreateOutputTestByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateOutputTestByIDResponse) GetObject() *CreateOutputTestByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
