// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateInputResponseBody - a list of Input objects
type CreateInputResponseBody struct {
	// number of items present in the items array
	Count *int64             `json:"count,omitempty"`
	Items []components.Input `json:"items,omitempty"`
}

func (o *CreateInputResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateInputResponseBody) GetItems() []components.Input {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateInputResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Input objects
	Object *CreateInputResponseBody
}

func (o *CreateInputResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateInputResponse) GetObject() *CreateInputResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
