// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeletePacksByIDRequest struct {
	// Pack name
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeletePacksByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeletePacksByIDResponseBody - a list of PackInstallInfo objects
type DeletePacksByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                       `json:"count,omitempty"`
	Items []components.PackInstallInfo `json:"items,omitempty"`
}

func (o *DeletePacksByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeletePacksByIDResponseBody) GetItems() []components.PackInstallInfo {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeletePacksByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of PackInstallInfo objects
	Object *DeletePacksByIDResponseBody
}

func (o *DeletePacksByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeletePacksByIDResponse) GetObject() *DeletePacksByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
