// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteOutputPqByIDRequest struct {
	// Destination Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteOutputPqByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteOutputPqByIDResponseBody - a list of any objects
type DeleteOutputPqByIDResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *DeleteOutputPqByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeleteOutputPqByIDResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteOutputPqByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *DeleteOutputPqByIDResponseBody
}

func (o *DeleteOutputPqByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteOutputPqByIDResponse) GetObject() *DeleteOutputPqByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
