// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeletePipelineByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeletePipelineByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeletePipelineByIDResponseBody - a list of Pipeline objects
type DeletePipelineByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.Pipeline `json:"items,omitempty"`
}

func (o *DeletePipelineByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *DeletePipelineByIDResponseBody) GetItems() []components.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeletePipelineByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Pipeline objects
	Object *DeletePipelineByIDResponseBody
}

func (o *DeletePipelineByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeletePipelineByIDResponse) GetObject() *DeletePipelineByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
