// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetCriblLakeDatasetByLakeIDRequest struct {
	// lake id that contains the Datasets
	LakeID string `pathParam:"style=simple,explode=false,name=lakeId"`
}

func (o *GetCriblLakeDatasetByLakeIDRequest) GetLakeID() string {
	if o == nil {
		return ""
	}
	return o.LakeID
}

// GetCriblLakeDatasetByLakeIDResponseBody - a list of CriblLakeDataset objects
type GetCriblLakeDatasetByLakeIDResponseBody struct {
	// number of items present in the items array
	Count *int64                        `json:"count,omitempty"`
	Items []components.CriblLakeDataset `json:"items,omitempty"`
}

func (o *GetCriblLakeDatasetByLakeIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetCriblLakeDatasetByLakeIDResponseBody) GetItems() []components.CriblLakeDataset {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetCriblLakeDatasetByLakeIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of CriblLakeDataset objects
	Object *GetCriblLakeDatasetByLakeIDResponseBody
}

func (o *GetCriblLakeDatasetByLakeIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCriblLakeDatasetByLakeIDResponse) GetObject() *GetCriblLakeDatasetByLakeIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
