// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetGroupsConfigVersionByIDRequest struct {
	// Group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetGroupsConfigVersionByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetGroupsConfigVersionByIDResponseBody - a list of string objects
type GetGroupsConfigVersionByIDResponseBody struct {
	// number of items present in the items array
	Count *int64   `json:"count,omitempty"`
	Items []string `json:"items,omitempty"`
}

func (o *GetGroupsConfigVersionByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetGroupsConfigVersionByIDResponseBody) GetItems() []string {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetGroupsConfigVersionByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of string objects
	Object *GetGroupsConfigVersionByIDResponseBody
}

func (o *GetGroupsConfigVersionByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetGroupsConfigVersionByIDResponse) GetObject() *GetGroupsConfigVersionByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
