// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

// GetGroupsACLByIDType - resource type by which to filter access levels
type GetGroupsACLByIDType string

const (
	GetGroupsACLByIDTypeGroups           GetGroupsACLByIDType = "groups"
	GetGroupsACLByIDTypeDatasets         GetGroupsACLByIDType = "datasets"
	GetGroupsACLByIDTypeDatasetProviders GetGroupsACLByIDType = "dataset-providers"
	GetGroupsACLByIDTypeProjects         GetGroupsACLByIDType = "projects"
	GetGroupsACLByIDTypeDashboards       GetGroupsACLByIDType = "dashboards"
	GetGroupsACLByIDTypeMacros           GetGroupsACLByIDType = "macros"
	GetGroupsACLByIDTypeNotebooks        GetGroupsACLByIDType = "notebooks"
	GetGroupsACLByIDTypeInsights         GetGroupsACLByIDType = "insights"
)

func (e GetGroupsACLByIDType) ToPointer() *GetGroupsACLByIDType {
	return &e
}
func (e *GetGroupsACLByIDType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "groups":
		fallthrough
	case "datasets":
		fallthrough
	case "dataset-providers":
		fallthrough
	case "projects":
		fallthrough
	case "dashboards":
		fallthrough
	case "macros":
		fallthrough
	case "notebooks":
		fallthrough
	case "insights":
		*e = GetGroupsACLByIDType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetGroupsACLByIDType: %v", v)
	}
}

type GetGroupsACLByIDRequest struct {
	// Group id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// resource type by which to filter access levels
	Type *GetGroupsACLByIDType `queryParam:"style=form,explode=true,name=type"`
}

func (o *GetGroupsACLByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetGroupsACLByIDRequest) GetType() *GetGroupsACLByIDType {
	if o == nil {
		return nil
	}
	return o.Type
}

// GetGroupsACLByIDResponseBody - a list of UserAccessControlList objects
type GetGroupsACLByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                             `json:"count,omitempty"`
	Items []components.UserAccessControlList `json:"items,omitempty"`
}

func (o *GetGroupsACLByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetGroupsACLByIDResponseBody) GetItems() []components.UserAccessControlList {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetGroupsACLByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of UserAccessControlList objects
	Object *GetGroupsACLByIDResponseBody
}

func (o *GetGroupsACLByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetGroupsACLByIDResponse) GetObject() *GetGroupsACLByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
