// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetInputByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetInputByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetInputByIDResponseBody - a list of Source objects
type GetInputByIDResponseBody struct {
	// number of items present in the items array
	Count *int64             `json:"count,omitempty"`
	Items []components.Input `json:"items,omitempty"`
}

func (o *GetInputByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetInputByIDResponseBody) GetItems() []components.Input {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetInputByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Source objects
	Object *GetInputByIDResponseBody
}

func (o *GetInputByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetInputByIDResponse) GetObject() *GetInputByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
