// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOutputSamplesByIDRequest struct {
	// Output Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetOutputSamplesByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetOutputSamplesByIDResponseBody - a list of OutputSamplesResponse objects
type GetOutputSamplesByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                             `json:"count,omitempty"`
	Items []components.OutputSamplesResponse `json:"items,omitempty"`
}

func (o *GetOutputSamplesByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetOutputSamplesByIDResponseBody) GetItems() []components.OutputSamplesResponse {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetOutputSamplesByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of OutputSamplesResponse objects
	Object *GetOutputSamplesByIDResponseBody
}

func (o *GetOutputSamplesByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOutputSamplesByIDResponse) GetObject() *GetOutputSamplesByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
