// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOutputByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetOutputByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetOutputByIDResponseBody - a list of Destination objects
type GetOutputByIDResponseBody struct {
	// number of items present in the items array
	Count *int64              `json:"count,omitempty"`
	Items []components.Output `json:"items,omitempty"`
}

func (o *GetOutputByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetOutputByIDResponseBody) GetItems() []components.Output {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetOutputByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Destination objects
	Object *GetOutputByIDResponseBody
}

func (o *GetOutputByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOutputByIDResponse) GetObject() *GetOutputByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
