// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOutputPqByIDRequest struct {
	// Output Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetOutputPqByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetOutputPqByIDResponseBody - a list of any objects
type GetOutputPqByIDResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *GetOutputPqByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetOutputPqByIDResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetOutputPqByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *GetOutputPqByIDResponseBody
}

func (o *GetOutputPqByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOutputPqByIDResponse) GetObject() *GetOutputPqByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
