// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetPipelineByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetPipelineByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetPipelineByIDResponseBody - a list of Pipeline objects
type GetPipelineByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.Pipeline `json:"items,omitempty"`
}

func (o *GetPipelineByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetPipelineByIDResponseBody) GetItems() []components.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetPipelineByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Pipeline objects
	Object *GetPipelineByIDResponseBody
}

func (o *GetPipelineByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPipelineByIDResponse) GetObject() *GetPipelineByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
