// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetPacksRequest struct {
	// Comma separated list of entities, "outputs", "inputs"
	With *string `queryParam:"style=form,explode=true,name=with"`
}

func (o *GetPacksRequest) GetWith() *string {
	if o == nil {
		return nil
	}
	return o.With
}

// GetPacksResponseBody - a list of PackInfo objects
type GetPacksResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.PackInfo `json:"items,omitempty"`
}

func (o *GetPacksResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetPacksResponseBody) GetItems() []components.PackInfo {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetPacksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of PackInfo objects
	Object *GetPacksResponseBody
}

func (o *GetPacksResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPacksResponse) GetObject() *GetPacksResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
