// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

// GetProductsGroupsByProductProduct - Cribl Product
type GetProductsGroupsByProductProduct string

const (
	GetProductsGroupsByProductProductStream GetProductsGroupsByProductProduct = "stream"
	GetProductsGroupsByProductProductEdge   GetProductsGroupsByProductProduct = "edge"
)

func (e GetProductsGroupsByProductProduct) ToPointer() *GetProductsGroupsByProductProduct {
	return &e
}
func (e *GetProductsGroupsByProductProduct) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stream":
		fallthrough
	case "edge":
		*e = GetProductsGroupsByProductProduct(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetProductsGroupsByProductProduct: %v", v)
	}
}

type GetProductsGroupsByProductRequest struct {
	// fields to add to results: git.commit, git.localChanges, git.log
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// Cribl Product
	Product GetProductsGroupsByProductProduct `pathParam:"style=simple,explode=false,name=product"`
}

func (o *GetProductsGroupsByProductRequest) GetFields() *string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *GetProductsGroupsByProductRequest) GetProduct() GetProductsGroupsByProductProduct {
	if o == nil {
		return GetProductsGroupsByProductProduct("")
	}
	return o.Product
}

// GetProductsGroupsByProductResponseBody - a list of ConfigGroup objects
type GetProductsGroupsByProductResponseBody struct {
	// number of items present in the items array
	Count *int64                   `json:"count,omitempty"`
	Items []components.ConfigGroup `json:"items,omitempty"`
}

func (o *GetProductsGroupsByProductResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetProductsGroupsByProductResponseBody) GetItems() []components.ConfigGroup {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetProductsGroupsByProductResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of ConfigGroup objects
	Object *GetProductsGroupsByProductResponseBody
}

func (o *GetProductsGroupsByProductResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetProductsGroupsByProductResponse) GetObject() *GetProductsGroupsByProductResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
