// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetRoutesByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetRoutesByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetRoutesByIDResponseBody - a list of Routes objects
type GetRoutesByIDResponseBody struct {
	// number of items present in the items array
	Count *int64              `json:"count,omitempty"`
	Items []components.Routes `json:"items,omitempty"`
}

func (o *GetRoutesByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetRoutesByIDResponseBody) GetItems() []components.Routes {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetRoutesByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Routes objects
	Object *GetRoutesByIDResponseBody
}

func (o *GetRoutesByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRoutesByIDResponse) GetObject() *GetRoutesByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
