// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSummaryWorkersRequest struct {
	// Filter expression evaluated against nodes
	FilterExp *string `queryParam:"style=form,explode=true,name=filterExp"`
}

func (o *GetSummaryWorkersRequest) GetFilterExp() *string {
	if o == nil {
		return nil
	}
	return o.FilterExp
}

// GetSummaryWorkersResponseBody - a list of number objects
type GetSummaryWorkersResponseBody struct {
	// number of items present in the items array
	Count *int64    `json:"count,omitempty"`
	Items []float64 `json:"items,omitempty"`
}

func (o *GetSummaryWorkersResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetSummaryWorkersResponseBody) GetItems() []float64 {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSummaryWorkersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of number objects
	Object *GetSummaryWorkersResponseBody
}

func (o *GetSummaryWorkersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSummaryWorkersResponse) GetObject() *GetSummaryWorkersResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
