// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetVersionFilesRequest struct {
	// Group ID
	Group *string `queryParam:"style=form,explode=true,name=group"`
	// Commit ID
	ID *string `queryParam:"style=form,explode=true,name=ID"`
}

func (o *GetVersionFilesRequest) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *GetVersionFilesRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

// GetVersionFilesResponseBody - a list of GitFilesResponse objects
type GetVersionFilesResponseBody struct {
	// number of items present in the items array
	Count *int64                        `json:"count,omitempty"`
	Items []components.GitFilesResponse `json:"items,omitempty"`
}

func (o *GetVersionFilesResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetVersionFilesResponseBody) GetItems() []components.GitFilesResponse {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetVersionFilesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of GitFilesResponse objects
	Object *GetVersionFilesResponseBody
}

func (o *GetVersionFilesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVersionFilesResponse) GetObject() *GetVersionFilesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
