// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetVersionCountRequest struct {
	// Group ID
	Group *string `queryParam:"style=form,explode=true,name=group"`
	// Commit ID
	ID *string `queryParam:"style=form,explode=true,name=ID"`
}

func (o *GetVersionCountRequest) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *GetVersionCountRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

// GetVersionCountResponseBody - a list of any objects
type GetVersionCountResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *GetVersionCountResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetVersionCountResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetVersionCountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *GetVersionCountResponseBody
}

func (o *GetVersionCountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVersionCountResponse) GetObject() *GetVersionCountResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
