// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetVersionStatusRequest struct {
	// Group ID
	Group *string `queryParam:"style=form,explode=true,name=group"`
}

func (o *GetVersionStatusRequest) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

// GetVersionStatusResponseBody - a list of GitStatusResult objects
type GetVersionStatusResponseBody struct {
	// number of items present in the items array
	Count *int64                       `json:"count,omitempty"`
	Items []components.GitStatusResult `json:"items,omitempty"`
}

func (o *GetVersionStatusResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetVersionStatusResponseBody) GetItems() []components.GitStatusResult {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetVersionStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of GitStatusResult objects
	Object *GetVersionStatusResponseBody
}

func (o *GetVersionStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVersionStatusResponse) GetObject() *GetVersionStatusResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
