// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetVersionDiffRequest struct {
	// Commit hash (default is HEAD)
	Commit *string `queryParam:"style=form,explode=true,name=commit"`
	// Group ID
	Group *string `queryParam:"style=form,explode=true,name=group"`
	// Filename
	Filename *string `queryParam:"style=form,explode=true,name=filename"`
	// Limit maximum lines in the diff
	DiffLineLimit *float64 `queryParam:"style=form,explode=true,name=diffLineLimit"`
}

func (o *GetVersionDiffRequest) GetCommit() *string {
	if o == nil {
		return nil
	}
	return o.Commit
}

func (o *GetVersionDiffRequest) GetGroup() *string {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *GetVersionDiffRequest) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

func (o *GetVersionDiffRequest) GetDiffLineLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.DiffLineLimit
}

// GetVersionDiffResponseBody - a list of any objects
type GetVersionDiffResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *GetVersionDiffResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetVersionDiffResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetVersionDiffResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *GetVersionDiffResponseBody
}

func (o *GetVersionDiffResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVersionDiffResponse) GetObject() *GetVersionDiffResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
