// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// GetVersionInfoResponseBody - a list of GitInfo objects
type GetVersionInfoResponseBody struct {
	// number of items present in the items array
	Count *int64               `json:"count,omitempty"`
	Items []components.GitInfo `json:"items,omitempty"`
}

func (o *GetVersionInfoResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetVersionInfoResponseBody) GetItems() []components.GitInfo {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetVersionInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of GitInfo objects
	Object *GetVersionInfoResponseBody
}

func (o *GetVersionInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVersionInfoResponse) GetObject() *GetVersionInfoResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
