// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetWorkersRequest struct {
	// Filter expression evaluated against nodes
	FilterExp *string `queryParam:"style=form,explode=true,name=filterExp"`
	// Sorting object (JSON stringified) expression evaluated against nodes
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Sorting expression evaluated against nodes
	SortExp *string `queryParam:"style=form,explode=true,name=sortExp"`
	// Maximum number of nodes to return
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Pagination offset
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Filter object (JSON stringified) to select nodes
	Filter *string `queryParam:"style=form,explode=true,name=filter"`
}

func (o *GetWorkersRequest) GetFilterExp() *string {
	if o == nil {
		return nil
	}
	return o.FilterExp
}

func (o *GetWorkersRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *GetWorkersRequest) GetSortExp() *string {
	if o == nil {
		return nil
	}
	return o.SortExp
}

func (o *GetWorkersRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetWorkersRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetWorkersRequest) GetFilter() *string {
	if o == nil {
		return nil
	}
	return o.Filter
}

// GetWorkersResponseBody - a list of MasterWorkerEntry objects
type GetWorkersResponseBody struct {
	// number of items present in the items array
	Count *int64                         `json:"count,omitempty"`
	Items []components.MasterWorkerEntry `json:"items,omitempty"`
}

func (o *GetWorkersResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetWorkersResponseBody) GetItems() []components.MasterWorkerEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetWorkersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of MasterWorkerEntry objects
	Object *GetWorkersResponseBody
}

func (o *GetWorkersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWorkersResponse) GetObject() *GetWorkersResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
