// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListInputResponseBody - a list of Source objects
type ListInputResponseBody struct {
	// number of items present in the items array
	Count *int64             `json:"count,omitempty"`
	Items []components.Input `json:"items,omitempty"`
}

func (o *ListInputResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListInputResponseBody) GetItems() []components.Input {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListInputResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Source objects
	Object *ListInputResponseBody
}

func (o *ListInputResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListInputResponse) GetObject() *ListInputResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
