// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListPipelineResponseBody - a list of Pipeline objects
type ListPipelineResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.Pipeline `json:"items,omitempty"`
}

func (o *ListPipelineResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListPipelineResponseBody) GetItems() []components.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListPipelineResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Pipeline objects
	Object *ListPipelineResponseBody
}

func (o *ListPipelineResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListPipelineResponse) GetObject() *ListPipelineResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
