// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListOutputResponseBody - a list of Output objects
type ListOutputResponseBody struct {
	// number of items present in the items array
	Count *int64              `json:"count,omitempty"`
	Items []components.Output `json:"items,omitempty"`
}

func (o *ListOutputResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ListOutputResponseBody) GetItems() []components.Output {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListOutputResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Output objects
	Object *ListOutputResponseBody
}

func (o *ListOutputResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListOutputResponse) GetObject() *ListOutputResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
