// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type LoginResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authentication token
	AuthToken *components.AuthToken
}

func (o *LoginResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *LoginResponse) GetAuthToken() *components.AuthToken {
	if o == nil {
		return nil
	}
	return o.AuthToken
}
