// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateInputHecTokenByIDAndTokenRequest struct {
	// HEC Source id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// token to update
	Token string `pathParam:"style=simple,explode=false,name=token"`
	// UpdateHecTokenRequest object
	UpdateHecTokenRequest components.UpdateHecTokenRequest `request:"mediaType=application/json"`
}

func (o *UpdateInputHecTokenByIDAndTokenRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateInputHecTokenByIDAndTokenRequest) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *UpdateInputHecTokenByIDAndTokenRequest) GetUpdateHecTokenRequest() components.UpdateHecTokenRequest {
	if o == nil {
		return components.UpdateHecTokenRequest{}
	}
	return o.UpdateHecTokenRequest
}

// UpdateInputHecTokenByIDAndTokenResponseBody - a list of any objects
type UpdateInputHecTokenByIDAndTokenResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *UpdateInputHecTokenByIDAndTokenResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateInputHecTokenByIDAndTokenResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateInputHecTokenByIDAndTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *UpdateInputHecTokenByIDAndTokenResponseBody
}

func (o *UpdateInputHecTokenByIDAndTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateInputHecTokenByIDAndTokenResponse) GetObject() *UpdateInputHecTokenByIDAndTokenResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
