// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdatePipelineByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Pipeline object to be updated
	Pipeline components.Pipeline `request:"mediaType=application/json"`
}

func (o *UpdatePipelineByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdatePipelineByIDRequest) GetPipeline() components.Pipeline {
	if o == nil {
		return components.Pipeline{}
	}
	return o.Pipeline
}

// UpdatePipelineByIDResponseBody - a list of Pipeline objects
type UpdatePipelineByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                `json:"count,omitempty"`
	Items []components.Pipeline `json:"items,omitempty"`
}

func (o *UpdatePipelineByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdatePipelineByIDResponseBody) GetItems() []components.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdatePipelineByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Pipeline objects
	Object *UpdatePipelineByIDResponseBody
}

func (o *UpdatePipelineByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePipelineByIDResponse) GetObject() *UpdatePipelineByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
