// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// UpdateWorkersRestartResponseBody - a list of RestartResponse objects
type UpdateWorkersRestartResponseBody struct {
	// number of items present in the items array
	Count *int64                       `json:"count,omitempty"`
	Items []components.RestartResponse `json:"items,omitempty"`
}

func (o *UpdateWorkersRestartResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateWorkersRestartResponseBody) GetItems() []components.RestartResponse {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateWorkersRestartResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of RestartResponse objects
	Object *UpdateWorkersRestartResponseBody
}

func (o *UpdateWorkersRestartResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateWorkersRestartResponse) GetObject() *UpdateWorkersRestartResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
