// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateGroupsDeployByIDRequest struct {
	// Group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// DeployRequest object
	DeployRequest components.DeployRequest `request:"mediaType=application/json"`
}

func (o *UpdateGroupsDeployByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateGroupsDeployByIDRequest) GetDeployRequest() components.DeployRequest {
	if o == nil {
		return components.DeployRequest{}
	}
	return o.DeployRequest
}

// UpdateGroupsDeployByIDResponseBody - a list of ConfigGroup objects
type UpdateGroupsDeployByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                   `json:"count,omitempty"`
	Items []components.ConfigGroup `json:"items,omitempty"`
}

func (o *UpdateGroupsDeployByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateGroupsDeployByIDResponseBody) GetItems() []components.ConfigGroup {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateGroupsDeployByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of ConfigGroup objects
	Object *UpdateGroupsDeployByIDResponseBody
}

func (o *UpdateGroupsDeployByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateGroupsDeployByIDResponse) GetObject() *UpdateGroupsDeployByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
