// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateGroupsByIDRequest struct {
	// Group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// ConfigGroup object
	ConfigGroup components.ConfigGroup `request:"mediaType=application/json"`
}

func (o *UpdateGroupsByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateGroupsByIDRequest) GetConfigGroup() components.ConfigGroup {
	if o == nil {
		return components.ConfigGroup{}
	}
	return o.ConfigGroup
}

// UpdateGroupsByIDResponseBody - a list of ConfigGroup objects
type UpdateGroupsByIDResponseBody struct {
	// number of items present in the items array
	Count *int64                   `json:"count,omitempty"`
	Items []components.ConfigGroup `json:"items,omitempty"`
}

func (o *UpdateGroupsByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateGroupsByIDResponseBody) GetItems() []components.ConfigGroup {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateGroupsByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of ConfigGroup objects
	Object *UpdateGroupsByIDResponseBody
}

func (o *UpdateGroupsByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateGroupsByIDResponse) GetObject() *UpdateGroupsByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
