// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateInputByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Source object to be updated
	Input components.Input `request:"mediaType=application/json"`
}

func (o *UpdateInputByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateInputByIDRequest) GetInput() components.Input {
	if o == nil {
		return components.Input{}
	}
	return o.Input
}

// UpdateInputByIDResponseBody - a list of Source objects
type UpdateInputByIDResponseBody struct {
	// number of items present in the items array
	Count *int64             `json:"count,omitempty"`
	Items []components.Input `json:"items,omitempty"`
}

func (o *UpdateInputByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdateInputByIDResponseBody) GetItems() []components.Input {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateInputByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of Source objects
	Object *UpdateInputByIDResponseBody
}

func (o *UpdateInputByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateInputByIDResponse) GetObject() *UpdateInputByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
