// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdatePacksRequest struct {
	// the file to upload
	Filename *string `queryParam:"style=form,explode=true,name=filename"`
}

func (o *UpdatePacksRequest) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

// UpdatePacksResponseBody - a list of any objects
type UpdatePacksResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *UpdatePacksResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *UpdatePacksResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdatePacksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// a list of any objects
	Object *UpdatePacksResponseBody
}

func (o *UpdatePacksResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePacksResponse) GetObject() *UpdatePacksResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
