workflowVersion: 1.0.0
speakeasyVersion: 1.661.2
sources:
    Cribl API Reference:
        inputs:
            - location: https://raw.githubusercontent.com/criblio/cribl-openapi-spec/main/specs/control-plane.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference
targets:
    cribl-control-plane:
        target: python
        source: Cribl API Reference
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
        testing:
            enabled: false
